SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
]

SWIDEA_SITE/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.ideaHome,name='idea_home'),
    path('idea_create', views.ideaCreate, name="idea_create"),
    path('idea_detail/<int:id>', views.ideaDetail, name="idea_detail"),
    path('idea_update/<int:id>', views.ideaUpdate, name="idea_update"),
    path('idea_delete/<int:id>', views.ideaDelete, name="idea_delete"),

    path('dev_home', views.devHome,name='dev_home'),
    path('dev_create', views.devCreate, name="dev_create"),
    path('dev_detail/<int:id>', views.devDetail, name="dev_detail"),
    path('dev_update/<int:id>', views.devUpdate, name="dev_update"),
    path('dev_delete/<int:id>', views.devDelete, name="dev_delete"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/posts/models.py
from django.db import models

# Create your models here.
class DevTool(models.Model):
    name = models.CharField(max_length=50, verbose_name="명칭")
    kind = models.CharField(max_length=50, verbose_name="분류")
    content = models.TextField(verbose_name="설명")

class Idea(models.Model):
    title = models.CharField(max_length=50, verbose_name="제목")
    image = models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name="사진")
    content = models.TextField(verbose_name="내용")
    interest = models.IntegerField(verbose_name="관심도")
    dev_tool = models.ForeignKey(DevTool, on_delete=models.CASCADE, related_name='dev_tool')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

SWIDEA_SITE/posts/views.py
from django.shortcuts import redirect, render
from .models import Idea, DevTool


# Create your views here.
def ideaHome(request):
    sort = request.GET.get('sort', '')
    if sort == '':
        posts = Idea.objects.all()
    else:
        posts = Idea.objects.all().order_by(sort)

    context = {
        'posts' : posts
    }

    return render(request, template_name="posts/idea_home.html", context=context)

def ideaCreate(request):
    if request.method == "POST":
        title = request.POST["title"]
        image = request.FILES.get("image")
        content = request.POST["content"]
        interest = request.POST["interest"]
        tool_name = request.POST["dev_tool"]

        dev_tool = DevTool.objects.get(name = tool_name)
        new = Idea.objects.create(title=title, image=image, content=content, interest=interest, dev_tool=dev_tool)
        return redirect(f"/idea_detail/{new.id}")
    else:
        tools = DevTool.objects.all()
        context = {
            'tools' : tools
        }
        return render(request, template_name="posts/idea_create.html", context=context)

def ideaDetail(request, id):
    idea = Idea.objects.get(id=id)
    context = {
        'idea' : idea
    }

    return render(request, template_name='posts/idea_detail.html', context=context)

def ideaUpdate(request,id):
    if request.method == "POST":
        title = request.POST["title"]
        if request.FILES.get('file') is not None:
            image= request.FILES.get('file')
        else:
            image = Idea.objects.get(id=id).image
        content = request.POST["content"]
        interest = request.POST["interest"]
        tool_name = request.POST["dev_tool"]
        dev_tool = DevTool.objects.get(name = tool_name)
        Idea.objects.filter(id=id).update(title=title, image=image, content=content, interest=interest, dev_tool=dev_tool)
        return redirect(f"/idea_detail/{id}")
    else:
        idea = Idea.objects.get(id=id)
        tools = DevTool.objects.all()
        context = {
            "idea" : idea,
            "tools" : tools
        }
        return render(request, template_name="posts/idea_update.html", context=context)

def ideaDelete(request, id):
    if request.method == "POST":
        Idea.objects.filter(id=id).delete()
    return redirect("/")

def devHome(request):
    tools = DevTool.objects.all()
    context = {
        'tools' : tools
    }

    return render(request, template_name='posts/dev_home.html', context=context)

def devCreate(request):
    if request.method == "POST":
        name = request.POST["name"]
        kind = request.POST["kind"]
        content = request.POST["content"]
        
        new = DevTool.objects.create(name=name, kind=kind, content=content)

        return redirect(f"/dev_detail/{new.id}")
    else:
        
        context = {
            
        }
        return render(request, template_name="posts/dev_create.html", context=context)

def devDetail(request, id):
    tool = DevTool.objects.get(id=id)
    ideas = Idea.objects.filter(dev_tool = tool)
    context = {
        'tool' : tool,
        'ideas' : ideas
    }
    return render(request, template_name='posts/dev_detail.html', context=context)

def devUpdate(request, id):
    if request.method == "POST":
        name = request.POST["name"]
        kind = request.POST["kind"]
        content = request.POST["content"]
        
        DevTool.objects.filter(id=id).update(name=name, kind=kind, content=content)
        return redirect(f"/dev_detail/{id}")
    else:
        tool = DevTool.objects.get(id=id)
        context = {
            "tool" : tool
        }
        return render(request, template_name="posts/dev_update.html", context=context)

def devDelete(request, id):
    if request.method == "POST":
        DevTool.objects.filter(id=id).delete()
    return redirect("/dev_home")

SWIDEA_SITE/posts/templates/posts/dev_create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SWIDEA_SITE</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="nav justify-content-around">
      <a class="navbar-brand text-success" href="{% url 'posts:idea_home' %}"
        >My SW Idea Manage</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_create' %}"
        >아이디어 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_home' %}"
        >아이디어 관리</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_create' %}"
        >개별툴 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_home' %}"
        >개별툴 관리</a
      >
    </nav>
    <div class="container mt-5">
      <div class="top__container d-flex justify-content-center flex-wrap mb-5">
        <h5>DevTool Register</h5>
      </div>
      <div
        class="container align-items-center d-flex justify-content-center flex-column"
      >
        <form action="/dev_create" method="post">
          {% csrf_token %}
          <div class="my-1">
            <input
              class="w-100"
              type="text"
              name="name"
              placeholder="이름"
              required
            />
          </div>
          <div class="my-1">
            <input
              class="w-100"
              type="text"
              name="kind"
              placeholder="종류"
              required
            />
          </div>
          <div class="my-1">
            <textarea
              class="w-100"
              name="content"
              id=""
              cols="30"
              rows="10"
              required
            ></textarea>
          </div>

          <div>
            <input class="w-100" type="submit" value="생성하기" />
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/dev_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SWIDEA_SITE</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="nav justify-content-around">
      <a class="navbar-brand text-success" href="{% url 'posts:idea_home' %}"
        >My SW Idea Manage</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_create' %}"
        >아이디어 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_home' %}"
        >아이디어 관리</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_create' %}"
        >개별툴 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_home' %}"
        >개별툴 관리</a
      >
    </nav>
    <div class="container mt-5">
      <div class="top__container d-flex justify-content-center flex-wrap mb-5">
        <h5>DevTool Detail</h5>
      </div>
      <div class="container">
        <h5>{{tool.name}}</h5>
        <p>{{tool.kind}}</p>
        <p>{{tool.content}}</p>

        <strong>💡만들 수 있는 SW 목록</strong>
        {% for idea in ideas %}
        <a href="{% url 'posts:idea_detail' idea.id %}">{{ idea.title }}</a>
        {% endfor %}
      </div>
      <div class="container mt-5 d-flex justify-content-around">
        <form action="{% url 'posts:dev_delete' tool.id %}" method="post">
          {% csrf_token %}
          <button class="btn btn-danger">삭제</button>
        </form>
        <a href="{% url 'posts:dev_home' %}" class="btn btn-secondary">목록</a>
        <a href="{% url 'posts:dev_update' tool.id %}" class="btn btn-primary"
          >수정</a
        >
      </div>
    </div>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/dev_home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SWIDEA_SITE</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="nav justify-content-around">
      <a class="navbar-brand text-success" href="{% url 'posts:idea_home' %}"
        >My SW Idea Manage</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_create' %}"
        >아이디어 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_home' %}"
        >아이디어 관리</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_create' %}"
        >개별툴 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_home' %}"
        >개별툴 관리</a
      >
    </nav>
    <div class="container mt-5">
      <div class="top__container d-flex justify-content-center flex-wrap mb-5">
        <h5>DevTool List</h5>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th style="width: 20%" scope="col">명칭</th>
            <th style="width: 30%" scope="col">분류</th>
            <th style="width: 50%" scope="col">소개</th>
          </tr>
        </thead>
        <tbody>
          {% for tool in tools%}
          <tr>
            <th scope="row">
              <a
                class="text-dark text-decoration-none"
                href="{% url 'posts:dev_detail' tool.id %}"
                >{{tool.name}}</a
              >
            </th>
            <td>{{tool.kind}}</td>
            <td>{{tool.content}}</td>
          </tr>
          {% endfor%}
        </tbody>
      </table>
    </div>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/dev_update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SWIDEA_SITE</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="nav justify-content-around">
      <a class="navbar-brand text-success" href="{% url 'posts:idea_home' %}"
        >My SW Idea Manage</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_create' %}"
        >아이디어 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_home' %}"
        >아이디어 관리</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_create' %}"
        >개별툴 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_home' %}"
        >개별툴 관리</a
      >
    </nav>
    <div class="container mt-5">
      <div class="top__container d-flex justify-content-center flex-wrap mb-5">
        <h5>DevTool Detail Update</h5>
      </div>
      <div
        class="container align-items-center d-flex justify-content-center flex-column"
      >
        <form action="{% url 'posts:dev_update' tool.id%}" method="post">
          {% csrf_token %}
          <div class="my-1">
            <input
              class="w-100"
              type="text"
              name="name"
              placeholder="이름"
              value="{{tool.name}}"
              required
            />
          </div>
          <div class="my-1">
            <input
              class="w-100"
              type="text"
              name="kind"
              placeholder="종류"
              value="{{tool.kind}}"
              required
            />
          </div>
          <div class="my-1">
            <textarea
              class="w-100"
              name="content"
              id=""
              cols="30"
              rows="10"
              required
            >
{{tool.content}}</textarea
            >
          </div>

          <div>
            <input class="w-100" type="submit" value="수정하기" />
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/idea_create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SWIDEA_SITE</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="nav justify-content-around">
      <a class="navbar-brand text-success" href="{% url 'posts:idea_home' %}"
        >My SW Idea Manage</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_create' %}"
        >아이디어 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_home' %}"
        >아이디어 관리</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_create' %}"
        >개별툴 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_home' %}"
        >개별툴 관리</a
      >
    </nav>
    <div class="container mt-5">
      <div class="top__container d-flex justify-content-center flex-wrap mb-5">
        <h5>Idea Register</h5>
      </div>
    </div>

    <div
      class="container align-items-center d-flex justify-content-center flex-column"
    >
      <form action="/idea_create" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="my-1">
          <input
            class="w-100"
            type="text"
            name="title"
            placeholder="제목"
            required
          />
        </div>
        <input type="file" name="image" />
        <div class="my-1">
          <textarea
            class="w-100"
            name="content"
            id=""
            cols="30"
            rows="10"
            required
          ></textarea>
        </div>
        <div class="my-1">
          <input
            type="number"
            name="interest"
            placeholder="아이디어 관심도"
            required
          />
        </div>
        <div class="my-1">
          <span>예상 개발툴 : </span>
          <select name="dev_tool">
            <option value="" selected>-- 선택 --</option>
            {% for tool in tools%}
            <option value="{{tool.name}}">{{tool.name}}</option>
            {% endfor %}
          </select>
        </div>
        <div>
          <input class="w-100" type="submit" value="생성하기" />
        </div>
      </form>
    </div>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/idea_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SWIDEA_SITE</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="nav justify-content-around">
      <a class="navbar-brand text-success" href="{% url 'posts:idea_home' %}"
        >My SW Idea Manage</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_create' %}"
        >아이디어 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_home' %}"
        >아이디어 관리</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_create' %}"
        >개별툴 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_home' %}"
        >개별툴 관리</a
      >
    </nav>
    <div class="container mt-5">
      <div class="top__container d-flex justify-content-center flex-wrap mb-5">
        <h5>Idea Detail</h5>
      </div>
      <div class="container">
        <h4>{{idea.title}}</h4>
        <img src="{{idea.image.url}}" alt="" class="w-50" />
        <p>1. 아이디어 관심도 : {{idea.interest}}</p>
        <p>
          2. 예상 개발 툴 :
          <strong
            ><a
              class="text-decoration-none text-dark"
              href="{% url 'posts:dev_detail' idea.dev_tool.id%}"
              >{{idea.dev_tool.name}}</a
            ></strong
          >
        </p>
        <p>3. 아이디어 설명 : {{idea.content}}</p>
      </div>
      <div class="container mt-5 d-flex justify-content-around">
        <form action="{% url 'posts:idea_delete' idea.id %}" method="post">
          {% csrf_token %}
          <button class="btn btn-danger">삭제</button>
        </form>
        <a href="{% url 'posts:idea_home' %}" class="btn btn-secondary">목록</a>
        <a href="{% url 'posts:idea_update' idea.id %}" class="btn btn-primary"
          >수정</a
        >
      </div>
    </div>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/idea_home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SWIDEA_SITE</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="nav justify-content-around">
      <a class="navbar-brand text-success" href="{% url 'posts:idea_home' %}"
        >My SW Idea Manage</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_create' %}"
        >아이디어 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_home' %}"
        >아이디어 관리</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_create' %}"
        >개별툴 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_home' %}"
        >개별툴 관리</a
      >
    </nav>
    <div class="container mt-5">
      <div class="top__container d-flex justify-content-center flex-wrap mb-5">
        <h5>Idea List</h5>
      </div>
      <form action="{% url 'posts:idea_home' %}">
        {% csrf_token %}
        <select name="sort">
          <option value="" selected>-- 정렬 기준 --</option>
          <option value="title">이름 순</option>
          <option value="created_at">등록 순</option>
          <option value="-created_at">최신 순</option>
          <option value="-updated_at">최근 수정 순</option>
        </select>
        <input type="submit" value="정렬" />
      </form>

      <div class="card-group">
        {% for post in posts%}
        <div class="card">
          <img
            src="{{post.image.url}}"
            class="card-img-top img-thumbnail"
            alt="..."
          />
          <div class="card-body">
            <h5 class="card-title">
              <a
                href="{% url 'posts:idea_detail' post.id%}"
                class="text-decoration-none text-dark"
                >{{post.title}}</a
              >
            </h5>
            <p class="card-text">예상 개발 툴 : {{post.dev_tool.name}}</p>
            <p class="card-text">아이디어 관심도 : {{post.interest}}</p>
          </div>
        </div>
        {% endfor%}
      </div>
    </div>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/idea_update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SWIDEA_SITE</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="nav justify-content-around">
      <a class="navbar-brand text-success" href="{% url 'posts:idea_home' %}"
        >My SW Idea Manage</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_create' %}"
        >아이디어 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:idea_home' %}"
        >아이디어 관리</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_create' %}"
        >개별툴 등록</a
      >
      <a class="nav-link text-success" href="{% url 'posts:dev_home' %}"
        >개별툴 관리</a
      >
    </nav>
    <div class="container mt-5">
      <div class="top__container d-flex justify-content-center flex-wrap mb-5">
        <h5>Idea Detail Update</h5>
      </div>
    </div>
   
    <div class="container align-items-center d-flex justify-content-center flex-column">
      <form
        action="{% url 'posts:idea_update' idea.id%}"
        method="post"
      >
        {% csrf_token %}
        <div class="my-1">
          <input
            class='w-100'
            type="text"
            name="title"
            placeholder="제목"
            value="{{idea.title}}"
            required
          />
        </div>
        <p>현재 이미지 : {{idea.image}}</p>
        <p>변경 이미지</p>
        <input
          type="file"
          name="image"  
        />
        <div class="my-1">
          <textarea
            class='w-100'
            name="content"
            id=""
            cols="30"
            rows="10"
            required
          >{{idea.content}}</textarea>
        </div>
        <div class="my-1">
          <input
            type="number"
            name="interest"
            placeholder="아이디어 관심도"
            value="{{idea.interest}}"
            required
          />
        </div>  
        <div class="my-1">
          <span>예상 개발툴 : </span>
          <select name="dev_tool" id="cur">
            {% for tool in tools%}
            {% if tool.name == idea.dev_tool.name%}
            <option value="{{tool.name}}" selected>{{tool.name}}</option>
            {% else %}
            <option value="{{tool.name}}">{{tool.name}}</option>
            {% endif %}
            {% endfor %}
          </select>
        </div>
        <div>
          <input class='w-100'type="submit" value="수정하기" />
        </div>
      </form>
  </body>
</html>