myMovieReviews/reviews/urls.py
from django.urls import path 

from . import views

app_name = "reviews"

urlpatterns = [
    path('', views.home, name="home"),
    path('create', views.create, name="create"),
    path('search', views.search, name="search"),
    path('review/<int:id>', views.detail, name="detail"),
    path('modify/<int:id>', views.modify, name="modify"),
    path('delete/<int:id>', views.delete, name="delete"),
]

myMovieReviews/reviews/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title =  models.CharField(max_length=50, verbose_name="제목")
    release = models.IntegerField(verbose_name="개봉년도")
    genre = models.CharField(max_length=50, verbose_name="장르")
    star = models.FloatField(verbose_name="별점")
    time = models.IntegerField(verbose_name="러닝타임")
    content = models.TextField(verbose_name="리뷰")
    director = models.CharField(max_length=50, verbose_name="감독")
    actor = models.CharField(max_length=50, verbose_name="배우")
    img = models.TextField(verbose_name="이미지 링크")
    poster = models.TextField(verbose_name="포스터 링크", default='')

myMovieReviews/reviews/views.py
from django.shortcuts import redirect, render

from reviews.movie_info import searchInfo
from .models import Review

# Create your views here.
def home(request):
    sort = request.GET.get('sort','')
    if sort == '':
        reviews = Review.objects.all()
    else:
        reviews = Review.objects.all().order_by(sort)
    context = {
        "reviews" : reviews
    }

    return render(request, template_name="reviews/home.html", context=context)

def create(request):
    if request.method == "POST":
        title = request.POST["title"]
        release = request.POST["release"]
        genre = request.POST["genre"]
        star = request.POST["star"]
        time = request.POST["time"]
        content = request.POST["content"]
        director = request.POST["director"]
        actor = request.POST["actor"]
        img = request.POST["img"]
        poster = request.POST["poster"]

        Review.objects.create(title=title, release=release, genre=genre, star=star, time=time, content=content, director=director, actor=actor, img=img ,poster=poster)
        return redirect("/")
    
    else:
        title = request.GET.get("title")
        release = request.GET.get("release")
        genre = request.GET.get("genre")
        time = request.GET.get("time")
        director = request.GET.get("director")
        actor = request.GET.get("actor")
        img = request.GET.get("img")
        poster = request.GET.get("poster")

        if title == None:
            context = {}
        else:
            context = {
            'title':title,
            'release':release, 
            'genre':genre, 
            'time':time, 
            'director':director, 
            'actor':actor,
            'img':img,
            'poster':poster,
        }
        return render(request, template_name="reviews/create.html", context=context)

def search(request):
    if request.method == "POST":
        title = request.POST["title"]
        results = searchInfo(title)
        if results:
            context = {
            "results" : results
            }
            return render(request, template_name="reviews/search.html", context = context)
        else:
            context = {}
            return render(request, template_name="reviews/search.html", context = context)

def detail(request, id):
    review = Review.objects.get(id=id)
    
    context = {
        "review" : review
    }

    return render(request, template_name="reviews/detail.html", context=context)

def modify(request, id):
    if request.method == "POST":
        title = request.POST["title"]
        release = request.POST["release"]
        genre = request.POST["genre"]
        star = request.POST["star"]
        time = request.POST["time"]
        content = request.POST["content"]
        director = request.POST["director"]
        actor = request.POST["actor"]
        
        Review.objects.filter(id=id).update(title=title, release=release, genre=genre, star=star, time=time, content=content, director=director, actor=actor)
        return redirect(f"/review/{id}")
    else:
        review = Review.objects.get(id=id)
        context = {
            "review" : review
        }
        return render(request, template_name="reviews/modify.html", context=context)


def delete(request, id):
    if request.method == "POST":
        Review.objects.filter(id=id).delete()
    return redirect("/")

myMovieReviews/reviews/templates/reviews/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>My Movie reviews</title>
    <style>
      input[type="number"]::-webkit-outer-spin-button,
      input[type="number"]::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
      }
    </style>
  </head>
  <body>
    <div class="container mb-2">
      <form
        class="align-items-center d-flex justify-content-center flex-column"
        action="/search"
        method="post"
      >
        {% csrf_token %}
        <div class="my-2">
          <input type="text" name="title" placeholder="네이버에서 영화 검색" />
        </div>
        <div class="my-2">
          <input type="submit" value="Search" />
        </div>
      </form>
    </div>

    <div class="container">
      <form
        class="align-items-center d-flex justify-content-center flex-column"
        action="/create"
        method="post"
      >
        {% csrf_token %}
        <div class="my-1">
          <input
            type="text"
            name="title"
            placeholder="제목"
            value="{{title}}"
            required
          />
        </div>
        <div class="my-1">
          <input
            type="number"
            name="release"
            placeholder="개봉년도"
            value="{{release}}"
          />
        </div>
        <div class="my-1">
          <input
            type="text"
            name="genre"
            placeholder="장르"
            value="{{genre}}"
          />
        </div>
        <div class="my-1">
          <input
            type="number"
            name="star"
            step="0.01"
            placeholder="별점"
            required
          />
        </div>
        <div class="my-1">
          <input
            type="number"
            name="time"
            placeholder="러닝타임"
            value="{{time}}"
            required
          />
        </div>
        <div class="my-1">
          <textarea
            name="content"
            id=""
            cols="30"
            rows="10"
            required
          ></textarea>
        </div>
        <div class="my-1">
          <input
            type="text"
            name="director"
            placeholder="감독"
            value="{{director}}"
          />
        </div>
        <div class="my-1">
          <input
            type="text"
            name="actor"
            placeholder="배우"
            value="{{actor}}"
          />
        </div>
        <input
          type="text"
          name="img"
          placeholder="이미지"
          value="{{img}}"
          style="display: none"
        /><input
          type="text"
          name="poster"
          placeholder="이미지"
          value="{{poster}}"
          style="display: none"
        />

        <div>
          <input type="submit" value="Save" />
        </div>
      </form>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

myMovieReviews/reviews/templates/reviews/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>My Movie reviews</title>
    <style>
      a {
        text-decoration: none;
      }
      button {
        color: red;
        border: 0;
        background-color: transparent;
      }
    </style>
  </head>
  <body>
    {% load mathfilters %}
    <div class="container py-5">
      <div class="container">
        <ul class="nav fixed-top justify-content-between border-bottom">
          <li class="nav-item">
            <h3><a class="nav-link text-dark" href="/">my Movie reviews</a></h3>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'reviews:create' %}"
              >Add a New Review</a
            >
          </li>
        </ul>
      </div>
      <div class="container my-5" style="background-color: #c9ced3">
        <div class="d-flex align-items-center">
          <h3>{{ review.title }}</h3>

          <div class="px-3">
            <a href="{% url 'reviews:modify' review.id %}" class="text-success"
              >수정</a
            >
          </div>
          <form action="{% url 'reviews:delete' review.id %}" method="post">
            {% csrf_token %}
            <button>삭제</button>
          </form>
        </div>
        <div class="d-flex align-items-center">
          <img src="{{review.poster}}" alt="" />
          <div class="ms-5 w-100" style="background-color: #e3e8ed">
            <p>개봉년도: {{ review.release }}</p>
            <p>감독: {{review.director}}</p>
            <p>출연: {{review.actor}}</p>
            <p>장르: {{review.genre}}</p>
            <p>별점: {{review.star}}</p>
            <p>
              러닝타임: {{review.time|intdiv:60}}시간 {{review.time|mod:60}}분
            </p>
          </div>
        </div>
        <div class="py-2 my-3" style="background-color: #e3e8ed">
          {{review.content}}
        </div>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

myMovieReviews/reviews/templates/reviews/home.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>My Movie reviews</title>
    <style>
      a {
        text-decoration: none;
        color: gray;
      }
      a:hover {
        color: gray;
      }
    </style>
  </head>
  <body>
    {% load mathfilters %}
    <div class="container mb-5">
      <ul
        class="nav fixed-top justify-content-between bg-light border-bottom align-items-center"
      >
        <li class="nav-item">
          <h3><a class="nav-link text-dark" href="/">my Movie reviews</a></h3>
        </li>
        <form action="{% url 'reviews:home' %}">
          <select name="sort">
            <option value="title">제목 오름차순</option>
            <option value="-title">제목 내림차순</option>
            <option value="star">별점 오름차순</option>
            <option value="-star">별점 내림차순</option>
            <option value="time">러닝타임 오름차순</option>
            <option value="-time">러닝타임 내림차순</option>
          </select>
          <button class="btn btn-dark" type="submit" value="">정렬</button>
        </form>
        <li class="nav-item">
          <a class="nav-link text-dark" href="{% url 'reviews:create' %}"
            >Add a New Review</a
          >
        </li>
      </ul>
    </div>
    <div class="container py-3">
      <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for review in reviews %}
        <div class="col">
          <div class="card h-100">
            <div class="card-body" style="background-color: #c9ced3">
              <div
                class="d-flex align-items-center"
                style="background-color: #e3e8ed"
              >
                <img
                  src="{{review.img}}"
                  alt="..."
                  width="67px"
                  height="95px"
                />
                <div class="px-2">
                  <h5 class="card-title">
                    <a
                      href="{% url 'reviews:detail' review.id %}"
                      class="card-link"
                      >{{review.title}}</a
                    >
                  </h5>
                </div>
              </div>
              <div class="d-flex align-items-center flex-column mt-3 mb-0">
                <p class="mb-0">개봉년도: {{review.release}}</p>
                <p class="mb-0">장르: {{review.genre}}</p>
                <p class="mb-0">별점: {{review.star}}</p>
                <p class="mb-0">
                  러닝타임: {{review.time|intdiv:60}}시간
                  {{review.time|mod:60}}분
                </p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% comment %}
      <article>
        <h2>
          <a href="{% url 'reviews:detail' review.id %}">{{review.title}}</a>
        </h2>
        <p>{{review.release}}</p>
        <p>{{review.genre}}</p>
        <p>{{review.star}}</p>
      </article>
      {% endcomment %}
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

myMovieReviews/reviews/templates/reviews/modify.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>My Movie reviews</title>
    <style>
      input[type="number"]::-webkit-outer-spin-button,
      input[type="number"]::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <form
        class="align-items-center d-flex justify-content-center flex-column"
        action="{% url 'reviews:modify' review.id %}"
        method="post"
      >
        {% csrf_token %}
        <div class="my-1">
          <div>제목</div>
          <input
            type="text"
            name="title"
            placeholder="제목"
            value="{{review.title}}"
            required
          />
        </div>
        <div class="my-1">
          <div>개봉년도</div>
          <input
            type="number"
            name="release"
            placeholder="개봉년도"
            value="{{review.release}}"
          />
        </div>
        <div class="my-1">
          <div>장르</div>
          <input
            type="text"
            name="genre"
            placeholder="장르"
            value="{{review.genre}}"
          />
        </div>
        <div class="my-1">
          <div>별점</div>
          <input
            type="number"
            name="star"
            step="0.01"
            placeholder="별점"
            value="{{review.star}}"
            required
          />
        </div>
        <div class="my-1">
          <div>러닝타임</div>
          <input
            type="number"
            name="time"
            placeholder="러닝타임"
            value="{{review.time}}"
            required
          />
        </div>
        <div class="my-1">
          <div>리뷰</div>
          <textarea name="content" id="" cols="30" rows="10" required>
{{review.content}}</textarea
          >
        </div>
        <div class="my-1">
          <div>감독</div>
          <input
            type="text"
            name="director"
            placeholder="감독"
            value="{{review.director}}"
          />
        </div>
        <div class="my-2">
          <div>배우</div>
          <input
            type="text"
            name="actor"
            placeholder="배우"
            value="{{review.actor}}"
          />
        </div>

        <div>
          <input type="submit" value="Save" />
        </div>
      </form>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

myMovieReviews/reviews/templates/reviews/search.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>My Movie reviews</title>
  </head>
  <body>
    <p>검색결과: {{results|length}}</p>

    {% if results %} {% for result in results %}
    <form
      action="/create"
      class="align-items-center d-flex justify-content-center"
    >
      {% csrf_token %}
      <div class="m-2">
        <input
          type="text"
          name="title"
          placeholder="제목"
          value="{{result.0}}"
          readonly
        />
      </div>
      <div class="m-2">
        <input
          type="number"
          name="release"
          placeholder="개봉년도"
          value="{{result.4}}"
          readonly
        />
      </div>
      <div class="m-2">
        <input
          type="text"
          name="genre"
          placeholder="장르"
          value="{{result.1}}"
          readonly
        />
      </div>
      <div class="m-2">
        <input
          type="number"
          name="time"
          placeholder="러닝타임"
          value="{{result.3}}"
          readonly
        />
      </div>
      <div class="m-2">
        <input
          type="text"
          name="director"
          placeholder="감독"
          value="{{result.5}}"
          readonly
        />
      </div>
      <div class="m-2">
        <input
          type="text"
          name="actor"
          placeholder="배우"
          value="{{result.6}}"
          readonly
        />
      </div>
      <div class="m-2">
        <input
          type="text"
          name="img"
          placeholder="이미지링크"
          value="{{result.7}}"
          style="display: none"
          readonly
        />
      </div>
      <div class="m-2">
        <input
          type="text"
          name="poster"
          placeholder="이미지링크"
          value="{{result.8}}"
          style="display: none"
          readonly
        />
      </div>
      <div class="m-2">
        <input type="submit" value="Select" />
      </div>
    </form>
    {% endfor %} {%else%}
    <a class="nav-link text-dark" href="/">Home으로 이동</a>
    {%endif%}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>